# Generated by Django 5.1.2 on 2024-11-25 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('race', models.CharField(max_length=100)),
                ('objectif', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NourritureStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('poids_stock', models.FloatField()),
                ('provenance', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockVaccin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nbr_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('date_vet', models.DateField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangerCochon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('quantite_consomme', models.FloatField()),
                ('cochon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repas', to='managing.identite')),
                ('nourriture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consommations', to='managing.nourriturestock')),
            ],
        ),
        migrations.CreateModel(
            name='EnterStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateField()),
                ('quantite_entree', models.FloatField()),
                ('type_stock', models.CharField(choices=[('nourriture', 'Nourriture'), ('vaccin', 'Vaccin')], max_length=50)),
                ('nourriture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='managing.nourriturestock')),
                ('vaccin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='managing.stockvaccin')),
            ],
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('identite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='managing.identite')),
            ],
        ),
        migrations.CreateModel(
            name='Sante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('etat_visuel', models.CharField(max_length=255)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sante', to='managing.suivi')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinCochon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantite', models.IntegerField()),
                ('usage', models.CharField(max_length=255)),
                ('cochon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccins', to='managing.identite')),
                ('vaccin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisations', to='managing.stockvaccin')),
                ('veterinaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='managing.veterinaire')),
            ],
        ),
    ]
