# Generated by Django 5.1.2 on 2024-12-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identite',
            name='specificite',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
