# Generated by Django 5.1.2 on 2024-12-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0002_identite_specificite'),
    ]

    operations = [
        migrations.AddField(
            model_name='identite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
