# Generated by Django 5.1.2 on 2024-12-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0004_identite_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='identite',
            name='poids',
            field=models.IntegerField(null=True),
        ),
    ]
