# Generated by Django 5.1.2 on 2024-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managing', '0005_identite_poids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identite',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
